[package]
name = "minecraft_addon_controller"
version = "0.0.1"
authors = ["TOwInOK"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.21", features = ["serde"] }
pretty_env_logger = "0.5.0"
reqwest = "0.11.22"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
tokio = { version = "1.34.0", features = ["full"] }
toml = "0.8.8"
