[package]
name = "minecraft_addon_controller"
version = "0.0.1"
authors = ["TOwInOK"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { version = "0.17.8", features = ["tokio"] }
log = { version = "0.4.21", features = ["serde"] }
md-5 = "0.10.6"
notify = { version = "6.1.1", features = ["serde"] }
pretty_env_logger = "0.5.0"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.114"
sha1 = "0.10.6"
sha2 = "0.10.8"
tempfile = "3.10.1"
thiserror = "1.0.57"
tokio = { version = "1.34.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
toml = "0.8.8"
