[core]
provider = "purpur"
version = "1.20.4"
# build = "2160"
freeze = false
force_update = false

[plugins]
[plugins.simple-voice-chat]
[plugins.chunky]
[plugins.itemswapper]

[additions]
configPluguinsFrom = "git@github.com:TOwInOK/test.git"
key = "SUPEREKLy"
path_to_core = "core"
# path_to_mods = ""
path_to_plugins = "plugins"
path_to_lock = "config.lock"
