[core]
    # Выбери один из вариантов: Vanilla, Spigot, Bucket, Paper, Purpur, Forge, NeoForge, Fabric
    provider = "spigot"
    version = "1.10.1"
    # Замораживать ли объекты при наличии в системе
    freeze = false
    force_update = false

[plugins]
    [plugins.simple_voice_chat2]
    version = "ail5iPUK"
    channel = "beta"
    freeze = false
    update = false

    [plugins.cooler2]
    source = "hangar"
    version = "ail5iPUK"
    channel = "beta"
    freeze = false
    update = true

[additions]
configPluguinsFrom = "git@github.com:TOwInOK/test.git"
key = "SUPEREKLy"
