[core]
    # Выбери один из вариантов: vanilla, spigot, bucket, paper, purpur, forge, neoForge, fabric, folia, waterfall, velocity
    provider = "purpur"
    version = "1.15"
    # build = "459"
    # Замораживать ли объекты при наличии в системе
    freeze = false
    force_update = false

[plugins]
    [plugins.simple_voice_chat2]
    version = "ail5iPUK"
    channel = "beta"
    freeze = false
    update = false

    [plugins.cooler2]
    source = "hangar"
    version = "ail5iPUK"
    channel = "beta"
    freeze = false
    update = true

[additions]
configPluguinsFrom = "git@github.com:TOwInOK/test.git"
key = "SUPEREKLy"
