#Example of config file

[version]
#which version you want? [Vanila, Buckit, Spigot, Paper, Purpur]
core = "Vanila"
#First: any version if they have.
#Second: lock version. (stop update)
version = ["1.20.1", false]
#Example: version = ["1.20.1", false]
#We are loading version 1.20.1 with the tag FFFw2f
#Because the flag is "false", we no longer update this version to newer versions of same verion.

[plugins]
#load plugins from Modrinth
modrinth = [
    "Chunky",
    "Simple Voice Chat",
]
#load plugins from SpigotMC
spigot = []
#load plugins from PaperMC
paper = []

#list for lock of update | plugins
frozen = []