[core]
    # Выбери один из вариантов: vanila, spigot, bucket, paper, purpur
    provider = "Paper"
    version = "1.14.4"
    # Замораживать ли объекты при наличии в системе
    freeze = false
    force_update = false

[plugins]
    [plugins.simple_voice_chat2]
    version = "ail5iPUK"
    chanel = "Stable"
    freez = false
    update = false

    [plugins.cooler2]
    source = "Spigot"
    version = "ail5iPUK"
    chanel = "Beta"
    freez = false
    update = true

    [plugins.best_plugin_without_any_param2]

[additions]
configPluguinsFrom = "git@github.com:TOwInOK/test.git"
key = "SUPEREKLy"
