calculate_hash = "Calculate hash..."
delete_exist_version = "Delete exist version!"
doest_need_to_update = "Does't need to update!"
done = "Done!"
download_file = "Download file..."
file_downloaded = "File downloaded!"
restart = "Restart..."
saving_file = "Saving file..."
start_new_iteration = "Start new iteration!"
stop_iteration = "Stop iteration!"
waiting_new_iteration = "Waiting new iteration..."
write_to_lock = "Write to lock!"
find_changes_in_settings = "Find some changes in settings!"
settings_changed = "Settings changed"
settings_has_rewrited = "Settings has rewrited"
settings_same = "Settings same"
intro = "MAC ready to work!"
init_work = "Generating link..."
finding_version = "Finding version..."
make_link = "Make link..."
start_remove_nonexist = "Start remove nonexist"
remove_nonexist = "Remove nonexist"
