calculate_hash = "Вычисление хеша..."
delete_exist_version = "Удаление существующей версии!"
doest_need_to_update = "Не требует обновления!"
done = "Готово!"
download_file = "Загрузка файла..."
file_downloaded = "Файл загружен!"
restart = "Перезапуск..."
saving_file = "Сохранение файла..."
start_new_iteration = "Начало новой итерации!"
stop_iteration = "Остановка итерации!"
waiting_new_iteration = "Ожидание новой итерации..."
write_to_lock = "Логирование файла!"
find_changes_in_settings = "Найдены изменения в настройках!"
settings_changed = "Настройки изменены"
settings_has_rewrited = "Настройки перезаписаны"
settings_same = "Настройки те же"
intro = "МАК готов к работе!"
init_work = "Генерация ссылки..."
finding_version = "Поиск версии..."
make_link = "Создание ссылки..."
start_remove_nonexist = "Удаление не логируемых файлов"
remove_nonexist = "Удаление не существующего:"
