# Пример конфигурации
# Sample of config

# freez - добавлять ли на проверку/скачивание если object присутствует.
# freez - whether to add for checking/downloading if object is present.

# Секция ядра / Core section
[core]
    # Выбери один из вариантов: vanila, spigot, bucket, paper, purpur
    # Choose one of the options: vanilla, spigot, bucket, paper, purpur
    provider = "paper"
    # Версия сервера (например, "1.14.4" или специальный код)
    # Server version (e.g., "1.14.4" or a special code)
    version = "1.14.4"
    build = ""
    #version = "latest" <- by default

    # Замораживать ли объекты при наличии в системе
    # Whether to freeze objects if present in the system
    freeze = false
    force_update = false

# Update - не требуется при загрузке, он нужен только когда freez = true, чтобы обновить на туже версию, либо принудительно обновить на самую последнюю, даже когда обновления нет.
# Update - not required on load, only needed when freez = true, to update to the same version, or forcibly update to the latest, even when there are no updates.
# Секция плагинов / Plugins section
[plugins]
    # Пример 1 - строчка
    # Example 1 - single line
    vc1 = {version = "ail5iPUK", channel = "stable", freeze = true, update = false}

    # Пример 2 - строчка
    # Example 2 - single line
    cooler1 = {source = "Spigot", version = "ail5iPUK", channel = "Beta", freeze = false, update = false}

    # Пример 3 - строчка
    # Example 3 - single line
    best_plugin_without_any_param1 = {}

    # Пример 1 - секция
    # Example 1 - section
    [plugins.simple_voice_chat2]
    version = "ail5iPUK"
    channel = "Stable"
    freeze = false
    update = false

    # Пример 2 - секция
    # Example 2 - section
    [plugins.cooler2]
    source = "Spigot"
    version = "ail5iPUK"
    channel = "Beta"
    freeze = false
    update = true

    # Пример 3 - секция
    # Example 3 - section
    [plugins.best_plugin_without_any_param2]
    #Дефолт: / Default:
    #source = Modrith
    #version = "Latest"
    #channel = "Stable"
    #freez = false
    #update = false

# Секция дополнений
# Additions section
[additions]
    # Git link для конфига
    # Git link for the config
    configPluguinsFrom = "git@github.com:TOwInOK/test.git"
    # Ключ если в привате
    # Key if in private
    key = "SUPEREKLy"
    # path_to_core = ""
    # path_to_mods = ""
    # path_to_plugins = ""
    # path_to_configs = ""