[core]
Provider = "vanilla"
Version = "Latest"
Freeze = false
ForceUpdate = false

[plugins.chunky]
source = "modrinth"
channel = "release"
freeze = false
force_update = false

[plugins.simple-voice-chat]
source = "modrinth"
channel = "release"
freeze = false
force_update = false

[additions]
config_plugins_from = "GitHub.link"
key = "GitHub.key"
