name: Rust

on:
  push:
    branches: [ "Rewriting" ]
  pull_request:
    branches: [ "Rewriting" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Lint it
      run: cargo clippy --no-deps --release

